### ISSUE TITLE
Yanking results

### ISSUE THREAD

**Issue by ArvinSKushwaha** [Apeiros-46B/qalc.nvim#1]
Hi!
Is there yet a way to yank the outputs of a qalc command? 

Thanks!

**Comment by Apeiros-46B** [comment]
Not yet, but this is the next thing I will work on when I'm less busy. For now, you can copy using your terminal emulator as a workaround (shift + mouse drag, control + shift + c)

**Comment by Apeiros-46B** [comment]
This has been added as the `:QalcYank` command. You can give it a register as an argument (see `:h setreg()` for the format) or you can just use it without any arguments and it will use the register in your config (new config field `yank_default_register`, same format as the argument)
