### ISSUE TITLE
Shows the Input as Output Without Calculating Expressions

### ISSUE THREAD

**Issue by mintycube** [Apeiros-46B/qalc.nvim#7]
### nvim version:

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

### qalc version

5.1.1

### OS

EndeavourOS Linux

### Issue:

The plugin is showing input as the output instead of calculating the expressions.
![qalc_screenshot](https://github.com/Apeiros-46B/qalc.nvim/assets/90507714/e6939c6e-6da5-4c8d-a75a-c775a384fa5d)

### minimal `init.lua`:

```lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

require("lazy").setup({
  spec = {
    -- add your plugins here
    {
      "Apeiros-46B/qalc.nvim",
      lazy = false,
      opts = {},
    }
  }
})
```

**Comment by Grueslayer** [comment]
@mintycube There was a bad behaviour using MS Windows, i've recently fixed. What OS are you running neovim on?

**Comment by Grueslayer** [comment]
@mintycube And I think I broke others.... may you try my local branch

```lua
  {
    "grueslayer/qalc.nvim",
    branch = "scratch_buffer",
  },
```

**Comment by mintycube** [comment]
@Grueslayer I am on EndeavourOS Linux. And your local branch seems to work ok.

**Comment by Grueslayer** [comment]
@Apeiros-46B shame on me, do you want a separate PR for that fix?

**Comment by Apeiros-46B** [comment]
I don't really have any preference, you can just leave it in the scratch buffer PR if that's easier @Grueslayer.
Sorry for being inactive; I've just been super busy with irl stuff lately

**Comment by Apeiros-46B** [comment]
Merged the fix. Thanks for your help!
